VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "coreos"
    config.vm.box_url = "http://storage.core-os.net/coreos/amd64-generic/dev-channel/coreos_production_vagrant.box"
    config.vm.network "private_network",
            ip: "172.12.8.150"

    # This will require sudo access when using "vagrant up"
    config.vm.synced_folder "./..", "/home/core/share",
        id: "core",
        :nfs => true,
        :mount_options => ['nolock,vers=3,udp']

    # plugin conflict
    if Vagrant.has_plugin?("vagrant-vbguest") then
        config.vbguest.auto_update = false
    end
end
